# config.yaml

project:
  name: Human-Activity-Recognition
  author: iam-dushyant

data:
  raw_path: data/raw/train.csv
  processed_path: data/processed/processed_data.csv
  test_path: data/raw/test.csv

model:
  type: random_forest
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  save_path: models/model.pkl

training:
  test_size: 0.2
  shuffle: true
  random_state: 42

logging:
  level: INFO
  log_dir: logs/

deployment:
  host: 0.0.0.0
  port: 8000
  api_prefix: /api
